/**
 * Golden cross-validation tests.
 *
 * These tests compare @s2js output against golden vectors generated by the
 * Python s2sphere library (which wraps the canonical C++ S2 implementation).
 * Any mismatch indicates a deviation from the reference implementation.
 */

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, it, expect } from "vitest";
import { vector, normalize as vecNormalize } from "@s2js/r3";
import { angleFromRadians } from "@s2js/s1";
import {
  cellIDFromLatLng,
  cellIDFromToken,
  toToken,
  face,
  level,
  isLeaf,
  parentAtLevel,
  children,
  contains,
  intersects,
  next,
  prev,
  edgeNeighbors,
  toPoint,
  toLatLng,
  stToUV,
  uvToST,
  faceFromXYZ,
} from "../src/cellId.js";
import { cellUnionFromCellIDs } from "../src/cellUnion.js";
import { capFromCenterAngle, capContainsPoint, capArea } from "../src/cap.js";

/** Earth constants (duplicated from @s2js/earth to avoid cross-package test dependency). */
const EARTH_RADIUS_KM = 6371.01;
const EARTH_RADIUS_M = 6371010;

// ---------------------------------------------------------------------------
// Load golden vectors
// ---------------------------------------------------------------------------

const vectorsPath = resolve(import.meta.dirname ?? ".", "../../../golden/vectors.json");
const golden = JSON.parse(readFileSync(vectorsPath, "utf-8"));

// ---------------------------------------------------------------------------
// CellID tests
// ---------------------------------------------------------------------------

describe("golden cross-validation", () => {
  describe("CellID", () => {
    describe("fromLatLng", () => {
      it.each(golden.cellId.fromLatLng)(
        "lat=$latDeg, lng=$lngDeg → token=$token, face=$face, level=$level",
        (tc: { latRad: number; lngRad: number; token: string; face: number; level: number; isLeaf: boolean }) => {
          const id = cellIDFromLatLng(tc.latRad, tc.lngRad);

          expect(toToken(id)).toBe(tc.token);
          expect(face(id)).toBe(tc.face);
          expect(level(id)).toBe(tc.level);
          expect(isLeaf(id)).toBe(tc.isLeaf);
        },
      );
    });

    describe("fromToken roundtrip", () => {
      it.each(golden.cellId.fromToken)(
        "token=$token → face=$face, level=$level",
        (tc: { token: string; face: number; level: number; latRad: number; lngRad: number }) => {
          const id = cellIDFromToken(tc.token);

          expect(face(id)).toBe(tc.face);
          expect(level(id)).toBe(tc.level);

          // LatLng roundtrip (within cell resolution)
          // At poles (|lat| ≈ π/2), longitude is undefined — skip lng comparison
          const ll = toLatLng(id);
          expect(ll.lat).toBeCloseTo(tc.latRad, 8);
          if (Math.abs(Math.abs(tc.latRad) - Math.PI / 2) > 0.01) {
            expect(ll.lng).toBeCloseTo(tc.lngRad, 8);
          }
        },
      );
    });

    describe("parentAtLevel", () => {
      it.each(golden.cellId.parentAtLevel)(
        "child=$childToken at level=$level → parent=$parentToken",
        (tc: { childToken: string; level: number; parentToken: string; parentFace: number }) => {
          const child = cellIDFromToken(tc.childToken);
          const p = parentAtLevel(child, tc.level);

          expect(toToken(p)).toBe(tc.parentToken);
          expect(face(p)).toBe(tc.parentFace);
          expect(level(p)).toBe(tc.level);
        },
      );
    });

    describe("children", () => {
      it.each(golden.cellId.children)(
        "parent=$parentToken → 4 children",
        (tc: { parentToken: string; parentLevel: number; childTokens: string[]; childLevels: number[] }) => {
          const p = cellIDFromToken(tc.parentToken);
          const ch = children(p);

          expect(ch).toHaveLength(4);
          for (let i = 0; i < 4; i++) {
            expect(toToken(ch[i]!)).toBe(tc.childTokens[i]);
            expect(level(ch[i]!)).toBe(tc.childLevels[i]);
          }
        },
      );
    });

    describe("contains/intersects", () => {
      it.each(golden.cellId.contains)(
        "a=$aToken, b=$bToken",
        (tc: { aToken: string; bToken: string; aContainsB: boolean; bContainsA: boolean; aIntersectsB: boolean }) => {
          const a = cellIDFromToken(tc.aToken);
          const b = cellIDFromToken(tc.bToken);

          expect(contains(a, b)).toBe(tc.aContainsB);
          expect(contains(b, a)).toBe(tc.bContainsA);
          expect(intersects(a, b)).toBe(tc.aIntersectsB);
        },
      );
    });

    describe("next/prev", () => {
      it.each(golden.cellId.nextPrev)(
        "token=$token → next=$nextToken, prev=$prevToken",
        (tc: { token: string; nextToken: string; prevToken: string }) => {
          const id = cellIDFromToken(tc.token);

          expect(toToken(next(id))).toBe(tc.nextToken);
          expect(toToken(prev(id))).toBe(tc.prevToken);
        },
      );
    });

    describe("edgeNeighbors", () => {
      it.each(golden.cellId.edgeNeighbors)(
        "token=$token → 4 neighbors",
        (tc: { token: string; level: number; neighborTokens: string[] }) => {
          const id = cellIDFromToken(tc.token);
          const neighbors = edgeNeighbors(id);

          expect(neighbors).toHaveLength(4);
          for (let i = 0; i < 4; i++) {
            expect(toToken(neighbors[i]!)).toBe(tc.neighborTokens[i]);
          }
        },
      );
    });

    describe("toPoint", () => {
      it.each(golden.cellId.toPoint)(
        "token=$token → (x, y, z)",
        (tc: { token: string; x: number; y: number; z: number }) => {
          const id = cellIDFromToken(tc.token);
          const p = toPoint(id);

          expect(p.x).toBeCloseTo(tc.x, 12);
          expect(p.y).toBeCloseTo(tc.y, 12);
          expect(p.z).toBeCloseTo(tc.z, 12);
        },
      );
    });

    describe("toLatLng", () => {
      it.each(golden.cellId.toLatLng)(
        "token=$token → lat/lng",
        (tc: { token: string; latRad: number; lngRad: number }) => {
          const id = cellIDFromToken(tc.token);
          const ll = toLatLng(id);

          expect(ll.lat).toBeCloseTo(tc.latRad, 8);
          // At poles (|lat| ≈ π/2), longitude is undefined — skip
          if (Math.abs(Math.abs(tc.latRad) - Math.PI / 2) > 0.01) {
            expect(ll.lng).toBeCloseTo(tc.lngRad, 8);
          }
        },
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Coordinate conversion tests
  // ---------------------------------------------------------------------------

  describe("coordinates", () => {
    describe("stToUV", () => {
      it.each(golden.coordinates.stToUV)("s=$s → u=$u", (tc: { s: number; u: number }) => {
        expect(stToUV(tc.s)).toBeCloseTo(tc.u, 14);
      });
    });

    describe("uvToST", () => {
      it.each(golden.coordinates.uvToST)("u=$u → s=$s", (tc: { u: number; s: number }) => {
        expect(uvToST(tc.u)).toBeCloseTo(tc.s, 14);
      });
    });

    describe("faceFromXYZ", () => {
      it.each(golden.coordinates.faceFromXYZ)(
        "($x, $y, $z) → face=$face",
        (tc: { x: number; y: number; z: number; face: number }) => {
          expect(faceFromXYZ(tc.x, tc.y, tc.z)).toBe(tc.face);
        },
      );
    });
  });

  // ---------------------------------------------------------------------------
  // CellUnion tests
  // ---------------------------------------------------------------------------

  describe("CellUnion", () => {
    describe("normalize", () => {
      it.each(golden.cellUnion.normalize)(
        "$description",
        (tc: { input: string[]; output: string[]; description: string }) => {
          const inputIds = tc.input.map((t) => cellIDFromToken(t));
          const normalized = cellUnionFromCellIDs(inputIds);
          const actualTokens = normalized.map((id) => toToken(id));

          expect(actualTokens).toEqual(tc.output);
        },
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Cap tests
  // ---------------------------------------------------------------------------

  describe("Cap", () => {
    describe("area", () => {
      it.each(golden.cap.area)(
        "$description",
        (tc: { centerX: number; centerY: number; centerZ: number; angleRad: number; area: number }) => {
          if (tc.angleRad < 0) {
            // Empty cap
            expect(capArea({ center: vector(tc.centerX, tc.centerY, tc.centerZ), radius: -1 as never })).toBe(0);
            return;
          }

          const cap = capFromCenterAngle(
            vecNormalize(vector(tc.centerX, tc.centerY, tc.centerZ)),
            angleFromRadians(tc.angleRad),
          );
          const actual = capArea(cap);

          expect(actual).toBeCloseTo(tc.area, 10);
        },
      );
    });

    describe("containsPoint", () => {
      it.each(golden.cap.containsPoint)(
        "$description",
        (tc: {
          centerX: number;
          centerY: number;
          centerZ: number;
          angleRad: number;
          pointX: number;
          pointY: number;
          pointZ: number;
          result: boolean;
        }) => {
          const cap = capFromCenterAngle(
            vecNormalize(vector(tc.centerX, tc.centerY, tc.centerZ)),
            angleFromRadians(tc.angleRad),
          );
          const point = vecNormalize(vector(tc.pointX, tc.pointY, tc.pointZ));

          expect(capContainsPoint(cap, point)).toBe(tc.result);
        },
      );
    });
  });

  // ---------------------------------------------------------------------------
  // Earth conversion tests
  // ---------------------------------------------------------------------------

  describe("earth", () => {
    describe("kmToAngle", () => {
      it.each(golden.earth.kmToAngle)("km=$km → angle=$angle", (tc: { km: number; angle: number }) => {
        const actual = tc.km / EARTH_RADIUS_KM;

        expect(actual).toBeCloseTo(tc.angle, 14);
      });
    });

    describe("mToAngle", () => {
      it.each(golden.earth.mToAngle)("m=$m → angle=$angle", (tc: { m: number; angle: number }) => {
        const actual = tc.m / EARTH_RADIUS_M;

        expect(actual).toBeCloseTo(tc.angle, 14);
      });
    });

    describe("roundtrip km", () => {
      it.each([1, 10, 100, 1000, 10000])("%d km roundtrip", (km) => {
        const angle = km / EARTH_RADIUS_KM;
        const actual = angle * EARTH_RADIUS_KM;

        expect(actual).toBeCloseTo(km, 10);
      });
    });

    describe("roundtrip m", () => {
      it.each([1, 100, 1000, 10000, 100000])("%d m roundtrip", (m) => {
        const angle = m / EARTH_RADIUS_M;
        const actual = angle * EARTH_RADIUS_M;

        expect(actual).toBeCloseTo(m, 6);
      });
    });
  });

  // ---------------------------------------------------------------------------
  // LatLngRect tests
  // ---------------------------------------------------------------------------

  describe("LatLngRect", () => {
    describe("area", () => {
      it.each(golden.latLngRect.area)(
        "$description",
        (tc: { latLoDeg: number; latHiDeg: number; lngLoDeg: number; lngHiDeg: number; area: number }) => {
          const latLo = (tc.latLoDeg * Math.PI) / 180;
          const latHi = (tc.latHiDeg * Math.PI) / 180;
          const lngLo = (tc.lngLoDeg * Math.PI) / 180;
          const lngHi = (tc.lngHiDeg * Math.PI) / 180;

          // Compute area directly: |sin(latHi) - sin(latLo)| * |lngHi - lngLo|
          const expected = Math.abs(Math.sin(latHi) - Math.sin(latLo)) * Math.abs(lngHi - lngLo);
          expect(expected).toBeCloseTo(tc.area, 10);
        },
      );
    });
  });
});
