export {
  type CellID,
  type FaceIJ,
  cellIDFromFace,
  cellIDFromFaceIJ,
  cellIDFromFacePosLevel,
  cellIDFromLatLng,
  cellIDFromPoint,
  cellIDFromToken,
  children,
  contains,
  edgeNeighbors,
  face,
  faceFromXYZ,
  faceIJFromCellID,
  faceUVFromXYZ,
  intersects,
  isFace,
  isLeaf,
  isValid,
  level,
  lsb,
  lsbForLevel,
  MAX_LEVEL,
  next,
  NONE,
  NUM_FACES,
  parent,
  parentAtLevel,
  prev,
  rangeMax,
  rangeMin,
  siTiToST,
  stToIJ,
  stToUV,
  toLatLng,
  toPoint,
  toToken,
  uvToST,
} from "./cellId.js";

export {
  type CellUnion,
  cellUnionContains,
  cellUnionContainsCellUnion,
  cellUnionDifference,
  cellUnionFromCellIDs,
  cellUnionIntersection,
  cellUnionIntersects,
  cellUnionIntersectsCellUnion,
  cellUnionUnion,
  normalize,
} from "./cellUnion.js";

export {
  type Cap,
  capAddCap,
  capAddPoint,
  capArea,
  capComplement,
  capContainsCap,
  capContainsPoint,
  capExpanded,
  capFromCenterAngle,
  capFromCenterArea,
  capFromCenterChordAngle,
  capFromCenterHeight,
  capIntersectsCap,
  emptyCap,
  fullCap,
  isEmptyCap,
  isFullCap,
} from "./cap.js";

export {
  type LatLngRect,
  emptyLatLngRect,
  fullLatLngRect,
  isEmptyLatLngRect,
  isFullLatLngRect,
  latLngRectAddLatLng,
  latLngRectArea,
  latLngRectCenter,
  latLngRectContainsLatLng,
  latLngRectContainsRect,
  latLngRectExpanded,
  latLngRectFromLatLng,
  latLngRectFromPointPair,
  latLngRectIntersection,
  latLngRectIntersectsRect,
  latLngRectUnion,
} from "./latLngRect.js";

export {
  type Crossing,
  type Sign,
  CROSSING,
  crossingSign,
  distanceFromSegment,
  interpolate,
  sign,
  SIGN,
} from "./predicates.js";

export { type Region, type RegionCovererOptions, covering, interiorCovering } from "./regionCoverer.js";

export {
  type Loop,
  isEmptyLoop,
  isFullLoop,
  isNormalized,
  loopArea,
  loopCentroid,
  loopContainsLoop,
  loopContainsPoint,
  loopFromPoints,
  loopIntersectsLoop,
  loopIsValid,
  normalizeLoop,
  numVertices,
  turningAngle,
  vertex,
} from "./loop.js";

export {
  type Polygon,
  numLoops,
  numVerticesPolygon,
  polygonArea,
  polygonCentroid,
  polygonContainsPoint,
  polygonFromLoop,
  polygonFromLoops,
  polygonFromVertices,
  polygonIsValid,
} from "./polygon.js";

export {
  type ClosestEdgeResult,
  type ClosestEdgeQueryOptions,
  findClosestEdgeInPolygon,
  findClosestEdgeToPoint,
  isDistanceLess,
  queryLoopContainsPoint,
  queryPolygonContainsPoint,
  signedDistanceToLoop,
} from "./queries.js";

export {
  polygonDifferenceApprox,
  polygonIntersectionApprox,
  polygonSymmetricDifferenceApprox,
  polygonUnionApprox,
} from "./booleanOperation.js";

export { convexHull } from "./convexHull.js";
