export {
  type Interval,
  addPoint,
  approxEquals,
  center,
  clampPoint,
  contains,
  containsInterval,
  directedHausdorffDistance,
  emptyInterval,
  equals,
  expanded,
  interiorContains,
  interiorContainsInterval,
  interiorIntersects,
  intersection,
  intersects,
  intervalFromPoint,
  intervalFromPointPair,
  isEmpty,
  length,
  union,
} from "./interval.js";
