export {
  type Point,
  add as pointAdd,
  crossProduct,
  dot as pointDot,
  mul as pointMul,
  norm as pointNorm,
  normalize as pointNormalize,
  ortho as pointOrtho,
  point,
  sub as pointSub,
} from "./point.js";

export {
  type Rect,
  addPoint,
  addRect,
  approxEquals,
  center,
  clampPoint,
  containsPoint,
  containsRect,
  emptyRect,
  expanded,
  expandedByMargin,
  hi,
  interiorContainsPoint,
  interiorContainsRect,
  interiorIntersectsRect,
  intersection,
  intersectsRect,
  isEmpty,
  isValid,
  lo,
  rectFromCenterSize,
  rectFromPoints,
  size,
  union,
  vertexIJ,
  vertices,
} from "./rect.js";
